const langData = {
    az: {
        nav_home: "Ana səhifə",
        nav_about: "Haqqımızda",
        nav_delivery: "Çatdırılma",
        nav_contact: "Əlaqə",
        nav_order: "Sifariş Et",
        hero_title: "Avtomobiliniz Üçün Premium Ayaq Altlıqları",
        hero_subtitle: "Avtomobilinizin salonuna mükəmməl uyğunlaşan, estetik, suya davamlı və uzunömürlü EVA, 3D və 5D altlıqları ilə səyahətinizi lüksə çevirin.",
        hero_btn: "Sifariş Et",
        about_title: "Haqqımızda",
        about_desc1: "PremiumCar.az olaraq 2019-cu ildən bəri avtomobilinizin interyerini qoruyan yüksək keyfiyyətli EVA, 3D və 5D ayaq altlıqları istehsal edirik.",
        about_desc2: "30-dan çox rəsmi avtosalonla əməkdaşlıq edərək, məhsullarımızı hər bir avtomobil modelinə tam uyğun olaraq qəlibləyirik.",
        read_more_btn: "Ardını Oxu",
        business_title: "7 İllik Təcrübə və Peşəkarlıq",
        about_business_p1: "PremiumCar.az 2019-cu ildən etibarən Azərbaycan bazarında avtomobil altlıqları istehsalı üzrə ixtisaslaşmışdır. Fəaliyyət göstərdiyimiz 7 il ərzində məqsədimiz hər zaman müştərilərimizə yüksək keyfiyyət, lüks və etibarlılıq təqdim etmək olmuşdur.",
        about_business_p2: "Biz ölkə daxilindəki rəsmi avtomobil distribyutorları və 30-dan çox avtosalonla sıx əməkdaşlıq edirik. Məhsullarımız sadəcə bir ayaq altlığı deyil, avtomobilin interyerinə tam uyğunlaşan, estetik və funksional bir qoruyucudur.",
        founder_title: "Təsisçi Haqqında",
        about_founder_name: "Sadıq Sadıqzadə İlqar oğlu",
        about_founder_p1: "Şirkətimizin təsisçisi Sadıq Sadıqzadə 2019-cu ildən etibarən bu biznesə rəhbərlik edir. Buna qədər o, bir çox fərqli layihələrin həyata keçirilməsində və müxtəlif bizneslərin idarə olunmasında iştirak etmişdir. Eyni zamanda ölkələrarası beynəlxalq ticarət sahəsində də böyük təcrübəyə malikdir.",
        about_founder_p2: "7 il ərzində xaricdə yaşayaraq qazandığı zəngin xarici təcrübəni Azərbaycana gətirən təsisçimiz, PremiumCar.az-ın fəaliyyətini tamamilə müasir və qlobal standartlara cavab verən səviyyədə qurmuşdur.",
        stat_years: "İllik Fəaliyyət",
        stat_salons: "Əməkdaş Avtosalon",
        stat_since: "Quruluş İli",
        stat_region: "Bütün Bölgələrə Çatdırılma",
        cta_title: "Sifariş Vermək İstəyirsiniz?",
        cta_desc: "Mütəxəssislərimiz avtomobilinizə uyğun altlığı seçmənizə kömək etmək üçün hazırdır.",
        feat_1: "Tam Avtomobilə Uyğunluq",
        feat_2: "Suya və Çirklənməyə Davamlı",
        feat_3: "Asan Təmizlənmə",
        delivery_title: "Bütün Bölgələrə Çatdırılma",
        delivery_desc: "Təkcə Bakı daxilində deyil, Azərbaycanın bütün bölgə və rayonlarına sürətli və təhlükəsiz çatdırılma xidməti göstəririk.",
        order_title: "Müraciət Et",
        order_subtitle: "Məlumatlarınızı daxil edin, avtomobilinizin modelinə uyğun altlıqları seçmək üçün mütəxəssislərimiz sizinlə əlaqə saxlayacaq.",
        form_name: "Adınız və Soyadınız",
        form_phone: "Əlaqə Nömrəsi",
        form_region: "Çatdırılma Bölgəsi (Şəhər/Rayon)",
        form_submit: "Göndər",
        contact_title: "Əlaqə və Ünvan",
        address_text: "Ünvan: Bakı şəhəri",
        hours_text: "İş saatları: Bazar ertəsi - Şənbə: 09:00 - 19:00",
        success_msg: "Sifarişiniz qəbul olundu! Mütəxəssislərimiz ən qısa zamanda sizinlə əlaqə saxlayacaq.",
        footer_text: "© 2026 PremiumCar.az. Bütün hüquqlar qorunur.",
        stat_clients: "Məmnun Müştəri",
        founder_photo_hint: "Şəkil tezliklə",
        founder_role: "Təsisçi & CEO",
        founder_short_bio: "2019-cu ildən bu biznesdə. Beynəlxalq ticarət təcrübəsi, 7 il xarici yaşam. PremiumCar.az-ı qlobal standartlarda quran şəxs.",
        products_title: "Məhsullarımız",
        products_subtitle: "Hər avtomobil modeli üçün xüsusi hazırlanmış premium altlıqlar",
        prod_badge_popular: "Populyar",
        prod_badge_new: "Yeni",
        prod1_name: "EVA Ayaq Altlığı",
        prod1_desc: "Şəkil və məlumat tezliklə əlavə ediləcək. Sifariş üçün bizimlə əlaqə saxlayın.",
        prod2_name: "3D Ayaq Altlığı",
        prod2_desc: "Şəkil və məlumat tezliklə əlavə ediləcək. Sifariş üçün bizimlə əlaqə saxlayın.",
        prod3_name: "5D Ayaq Altlığı",
        prod3_desc: "Şəkil və məlumat tezliklə əlavə ediləcək. Sifariş üçün bizimlə əlaqə saxlayın.",
        reviews_title: "Müştəri Rəyləri",
        reviews_subtitle: "Müştərilərimizin PremiumCar.az haqqında fikirləri",
        review1_text: "\"Altlıqlar əla keyfiyyətdədir, BMW-yə tam oturdu. Çox məmnun qaldım!\"",
        review1_name: "Anar M.",
        review1_car: "BMW 5 Series",
        review2_text: "\"Çox sürətli çatdırıldı, Gəncəyə sifarişi 2 gündə aldım. Material çox yüksək keyfiyyətlidir.\"",
        review2_name: "Elçin R.",
        review2_car: "Mercedes E-Class",
        review3_text: "\"Maşının salonunu tamamilə dəyişdi, çox zərif görünüş verdi. Tövsiyə edirəm!\"",
        review3_name: "Nigar H.",
        review3_car: "Toyota Camry",
        social_title: "Sosial Media",
        contact_full_page: "Ətraflı Əlaqə Səhifəsi",
        call_now: "İndi Zəng Et",
        write_whatsapp: "WhatsApp-a Yaz",
        send_email: "E-poçt Göndər",
        follow_instagram: "İzlə",
        working_hours_title: "İş Saatları",
        weekdays: "Bazar ertəsi – Cümə",
        saturday: "Şənbə",
        sunday: "Bazar",
        closed: "Bağlı"
    },
    ru: {
        nav_home: "Главная",
        nav_about: "О нас",
        nav_delivery: "Доставка",
        nav_contact: "Контакты",
        nav_order: "Заказать",
        hero_title: "Премиальные Автоковрики Для Вашего Авто",
        hero_subtitle: "Превратите каждую поездку в роскошь с идеально подходящими, эстетичными, водонепроницаемыми и долговечными ковриками EVA, 3D и 5D.",
        hero_btn: "Заказать",
        about_title: "О нас",
        about_desc1: "Как компания PremiumCar.az, с 2019 года мы производим высококачественные коврики EVA, 3D и 5D, защищающие интерьер вашего автомобиля.",
        about_desc2: "Сотрудничая с более чем 30 официальными автосалонами, мы формуем наши изделия точно под каждую модель автомобиля.",
        read_more_btn: "Читать далее",
        business_title: "7 лет опыта и профессионализма",
        about_business_p1: "С 2019 года PremiumCar.az специализируется на производстве автомобильных ковриков на рынке Азербайджана. За 7 лет нашей деятельности нашей целью всегда было предоставление клиентам высокого качества, роскоши и надежности.",
        about_business_p2: "Мы тесно сотрудничаем с официальными автодистрибьюторами и более чем 30 автосалонами страны. Наши продукты — это не просто коврики, а эстетичные и функциональные защитные элементы, идеально вписывающиеся в интерьер автомобиля.",
        founder_title: "Основатель компании",
        about_founder_name: "Садыг Садыгзаде Ильгар оглы",
        about_founder_p1: "Основатель компании Садыг Садыгзаде руководит этим бизнесом с 2019 года. До этого он принимал участие в реализации множества различных проектов и управлении несколькими бизнесами. Он также имеет большой опыт в сфере международной торговли.",
        about_founder_p2: "Прожив за границей 7 лет и привезя в Азербайджан богатый зарубежный опыт, наш основатель выстроил деятельность PremiumCar.az на совершенно современном уровне, отвечающем мировым стандартам.",
        stat_years: "лет деятельности",
        stat_salons: "Партнёрских салонов",
        stat_since: "Год основания",
        stat_region: "Доставка по всем регионам",
        cta_title: "Хотите сделать заказ?",
        cta_desc: "Наши специалисты готовы помочь вам выбрать подходящий коврик для вашего автомобиля.",
        feat_1: "Идеальная совместимость",
        feat_2: "Водонепроницаемые и грязеотталкивающие",
        feat_3: "Легко моются",
        delivery_title: "Доставка во все регионы",
        delivery_desc: "Мы обеспечиваем быструю и безопасную доставку не только в Баку, но и во все регионы и районы Азербайджана.",
        order_title: "Оформить заявку",
        order_subtitle: "Введите свои данные, и наши специалисты свяжутся с вами для подбора ковриков для вашей модели автомобиля.",
        form_name: "Имя и Фамилия",
        form_phone: "Номер телефона",
        form_region: "Регион доставки (Город/Район)",
        form_submit: "Отправить",
        contact_title: "Контакты и Адрес",
        address_text: "Адрес: г. Баку",
        hours_text: "Часы работы: Пн - Сб: 09:00 - 19:00",
        success_msg: "Ваш заказ принят! Наши специалисты свяжутся с вами в ближайшее время.",
        footer_text: "© 2026 PremiumCar.az. Все права защищены.",
        stat_clients: "Довольных клиентов",
        founder_photo_hint: "Фото скоро будет",
        founder_role: "Основатель и CEO",
        founder_short_bio: "В бизнесе с 2019 года. Опыт международной торговли, 7 лет за границей. Человек, построивший PremiumCar.az по мировым стандартам.",
        products_title: "Наши продукты",
        products_subtitle: "Премиальные коврики, изготовленные специально для каждой модели автомобиля",
        prod_badge_popular: "Популярно",
        prod_badge_new: "Новинка",
        prod1_name: "Коврики EVA",
        prod1_desc: "Фото и информация скоро появятся. Свяжитесь с нами для заказа.",
        prod2_name: "Коврики 3D",
        prod2_desc: "Фото и информация скоро появятся. Свяжитесь с нами для заказа.",
        prod3_name: "Коврики 5D",
        prod3_desc: "Фото и информация скоро появятся. Свяжитесь с нами для заказа.",
        reviews_title: "Отзывы клиентов",
        reviews_subtitle: "Что наши клиенты думают о PremiumCar.az",
        review1_text: "\"Коврики отличного качества, идеально подошли на BMW. Очень доволен!\"",
        review1_name: "Анар М.",
        review1_car: "BMW 5 Series",
        review2_text: "\"Очень быстрая доставка, получил заказ в Гяндже за 2 дня. Материал очень высокого качества.\"",
        review2_name: "Эльчин Р.",
        review2_car: "Mercedes E-Class",
        review3_text: "\"Полностью изменило салон машины, придало очень элегантный вид. Рекомендую!\"",
        review3_name: "Нигяр Г.",
        review3_car: "Toyota Camry",
        social_title: "Социальные сети",
        contact_full_page: "Полная страница контактов",
        call_now: "Позвонить сейчас",
        write_whatsapp: "Написать в WhatsApp",
        send_email: "Отправить E-mail",
        follow_instagram: "Подписаться",
        working_hours_title: "Часы работы",
        weekdays: "Понедельник – Пятница",
        saturday: "Суббота",
        sunday: "Воскресенье",
        closed: "Закрыто"
    }
};
